build: off  # отключаем встроенную в appveyor систему сборки

image: Ubuntu1804  # образ для сборки
stack: node 12  # окружение
cache: node_modules  # кеширование

branches:
  only:
    - master  # ветка git

install: npm i  # команда установки зависимостей
build_script: npm run build   # команда сборки
test_script: npm run lint && npm test  # скрипт тестирования
